#!/bin/bash
make utest_multiply
g++ -std=c++14 maketest.cpp -o maketest
./maketest test.csv > script
chmod u+x script

if [ -e test.csv ]; then
  rm test.csv
fi

echo "p,size,len,waksman,eval,3_primes,trans" > test.csv
./script
