#ifndef __THRESHOLDS_GEOMETRIC_INTERPOLATE_FFT_H
#define __THRESHOLDS_GEOMETRIC_INTERPOLATE_FFT_H
#define MIN_GEOMETRIC_FFT_INTERPOLATE_SMALL 2
#define MAX_GEOMETRIC_FFT_INTERPOLATE_SMALL 121
#define MIN_GEOMETRIC_FFT_INTERPOLATE_LARGE 2
#define MAX_GEOMETRIC_FFT_INTERPOLATE_LARGE 113
#define MIN_GEOMETRIC_FFT_INTERPOLATE_FFT 2
#define MAX_GEOMETRIC_FFT_INTERPOLATE_FFT 16
#endif

// Local Variables:
// mode: C++
// tab-width: 4
// indent-tabs-mode: nil
// c-basic-offset: 4
// End:
// vim:sts=4:sw=4:ts=4:et:sr:cino=>s,f0,{0,g0,(0,\:0,t0,+0,=s
